name: StrifeArena
version: 1.0.0
main: land.face.arena.StrifeArenaPlugin
author: Faceguy
description: Make sum mob arenas
depend:
  - Facecore
  - Strife
api-version: 1.16

permissions:
  arenas.exit:
    description: Exit arena when done
    default: true

commands:
  arena:
    usage: /<command>
    aliases: [arenaa]
    description: arenaz